settings:
  default-origin: human  # Default origin when resetting
  ability-cooldown: 30   # Global cooldown for abilities (seconds)
  use-placeholderapi: true  # Enable PlaceholderAPI support
  use-default-menu: true # If true, use plugin's menu. If false, disable it.

origins:
  frog:
    effects:
      - type: JUMP
        amplifier: 1
        duration: 999999 # Infinite effect
      - type: WATER_BREATHING
        amplifier: 0
        duration: 999999

  ravager:
    effects:
      - type: INCREASE_DAMAGE
        amplifier: 0
        duration: 999999
      - type: DAMAGE_RESISTANCE
        amplifier: 0
        duration: 999999

  sniffer:
    effects:
      - type: NIGHT_VISION
        amplifier: 0
        duration: 999999
      - type: FAST_DIGGING
        amplifier: 1
        duration: 999999

  chicken:
    effects:
      - type: SLOW_FALLING
        amplifier: 0
        duration: 999999

  wolf:
    effects:
      - type: INCREASE_DAMAGE
        amplifier: 0
        duration: 999999
      - type: REGENERATION
        amplifier: 0
        duration: 999999

  bee:
    effects:
      - type: SPEED
        amplifier: 1
        duration: 999999
      - type: FAST_DIGGING
        amplifier: 0
        duration: 999999

  cat:
    effects:
      - type: SPEED
        amplifier: 1
        duration: 999999
      - type: JUMP
        amplifier: 0
        duration: 999999
      - type: NIGHT_VISION
        amplifier: 0
        duration: 999999
