name: WildOrigins
main: Puk3p.wildorigins.WildOrigins
version: 1.0
api-version: 1.20
author: Puk3p
description: A plugin that allows players to select animal origins with special abilities.
commands:
  abilities:
    description: Shows the abilities of your current origin.
    usage: /abilities
  setorigin:
    description: Set a player's origin (admin only).
    usage: /setorigin <player> <origin>
    permission: wildorigins.admin
  resetorigin:
    description: Reset a player's origin to human.
    usage: /resetorigin <player>
    permission: wildorigins.admin
permissions:
  wildorigins.admin:
    description: Allows managing player origins.
    default: op
